var myFullName
console.log(myFullName);
myFullName="Ajay Mahajan";
console.log(myFullName);
myFullName='Ajay Dattatray Mahajan';
console.log(myFullName);
var mylove="I Love Only JS";
console.log(mylove);
var firstName="Ajay";
console.log("First Name:",firstName);
var lastName="mahajan";
console.log("Last Name:",lastName);
var age="21";
console.log("Age:",age);
var address="At-malkhed";
console.log("Address:",address);
var pin="Pincode:";
console.log(pin,"415539");
var gender="Male";
console.log("gender:",gender);
var marr="NA";
console.log("Married:",marr);