let result;
result='3'+2;
console.log(result);
console.log(`ans:'2' implicit converted into string`);
console.log(`_______________________________________________`);
result='3'+true;
console.log(result);
console.log(`ans:'true' implicit converted into string`);
console.log(`_______________________________________________`);
result='3'+undefined;
console.log(result);
console.log(`ans:'Undefined' implicit converted into string`);
console.log(`_______________________________________________`);
result='3'+null;
console.log(result);
console.log(`ans:'null' implicit converted into string`);
